options:
  extendDefault: true

reporter:
  class: whm\SmokeBundle\Util\CollectionReporter

rules:

  JsSyntaxValid:
    class: whm\Smoke\Rules\Js\SyntaxRule
    parameters:
      jsHintExecutable: jshint